import { Link } from 'react-router-dom';
import { useTheme } from '../hooks/useTheme';

const LAST_UPDATED = 'July 20, 2026';
const SUPPORT_EMAIL = 'support@potatoaihub.com';
const SITE_URL = 'https://potatoaihub.com';

export default function PrivacyPolicyPage() {
  useTheme();

  return (
    <div className="flex min-h-screen flex-col bg-surface-0">
      <header className="sticky top-0 z-10 border-b border-surface-3 bg-surface-1 px-6 py-3">
        <div className="mx-auto flex max-w-3xl items-center justify-between">
          <Link to="/login" className="flex items-center gap-2">
            <span className="text-xl" aria-hidden>🥔</span>
            <span className="font-semibold text-white">PotatoChat</span>
          </Link>
          <Link
            to="/login"
            className="text-sm text-potato-500 hover:text-potato-400"
          >
            Sign in
          </Link>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-10">
        <h1 className="mb-2 text-3xl font-bold text-white">Privacy Policy</h1>
        <p className="mb-8 text-sm text-gray-500">Last updated: {LAST_UPDATED}</p>

        <div className="prose prose-invert prose-sm max-w-none prose-headings:text-white prose-p:text-gray-300 prose-li:text-gray-300 prose-strong:text-white prose-a:text-potato-500 hover:prose-a:text-potato-400">
          <p>
            This Privacy Policy describes how PotatoAIHub (&ldquo;PotatoAIHub,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;),
            operating the PotatoChat service at{' '}
            <a href={SITE_URL}>{SITE_URL}</a> and related applications (together, the &ldquo;Service&rdquo;),
            collects, uses, and shares information about you.
          </p>
          <p>
            By creating an account or using the Service, you agree to this Privacy Policy.
            If you do not agree, please do not use the Service.
          </p>

          <h2>1. Who we are</h2>
          <p>
            PotatoChat is an AI chat product that lets you converse with third-party AI models,
            organise chats into projects, and purchase or use credits for usage.
            For privacy questions, contact us at{' '}
            <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
          </p>
          <p>
            <em>
              Legal entity name and registered address: [To be completed — insert your
              company/legal entity details here.]
            </em>
          </p>

          <h2>2. Information we collect</h2>

          <h3>2.1 Account and profile</h3>
          <ul>
            <li>Email address, username, and display name</li>
            <li>Password (stored hashed; we do not store plaintext passwords)</li>
            <li>Optional profile details such as avatar image</li>
            <li>
              If you sign in with Google or GitHub: identifiers and profile information those
              providers share with us (for example name, email, and avatar)
            </li>
          </ul>

          <h3>2.2 Chat and product content</h3>
          <ul>
            <li>Messages you send and responses generated by AI models</li>
            <li>Chat titles, projects, attachments you upload, and related metadata</li>
            <li>Shared-chat links you create and content exposed through those links</li>
            <li>Model selection, preferences, and similar product settings</li>
          </ul>

          <h3>2.3 Usage, credits, and billing</h3>
          <ul>
            <li>Credit balances, ledger events, and model/token usage records</li>
            <li>
              Payment and subscription information processed by Stripe (we do not store full
              card numbers on our servers; Stripe handles payment details)
            </li>
            <li>Plan type and billing-related account status</li>
          </ul>

          <h3>2.4 Technical and device data</h3>
          <ul>
            <li>IP address, browser or app type, device information, and approximate location derived from IP</li>
            <li>Log data (timestamps, request paths, error diagnostics) for security and reliability</li>
            <li>
              Local storage on your device for authentication tokens and UI preferences
              (for example theme)
            </li>
          </ul>

          <h3>2.5 Communications</h3>
          <ul>
            <li>Emails related to account verification, password reset, and service notices</li>
            <li>Support messages you send to us</li>
          </ul>

          <h2>3. How we use information</h2>
          <p>We use the information above to:</p>
          <ul>
            <li>Provide, operate, and improve the Service (including streaming chat responses)</li>
            <li>Authenticate you, secure accounts, and prevent abuse or fraud</li>
            <li>Process credits, subscriptions, and payments</li>
            <li>Send transactional emails (verification, password reset, billing notices)</li>
            <li>Respond to support requests and enforce our terms</li>
            <li>Comply with legal obligations and protect our rights</li>
          </ul>
          <p>
            We do not sell your personal information. We do not use your chat content to train
            our own foundation models. Content may be sent to third-party AI providers you select
            so they can generate responses (see below).
          </p>

          <h2>4. Third-party services</h2>
          <p>We share data with service providers only as needed to run PotatoChat:</p>
          <ul>
            <li>
              <strong>AI model providers</strong> (for example Anthropic, OpenAI, Google, and similar) —
              prompts, context, and related content are sent to the model you choose so a response
              can be generated. Their processing is subject to their own privacy policies.
            </li>
            <li>
              <strong>Stripe</strong> — payment processing and billing.
            </li>
            <li>
              <strong>Google / GitHub</strong> — if you use social sign-in.
            </li>
            <li>
              <strong>Hosting and infrastructure</strong> providers that store or transmit data on
              our behalf (for example cloud servers and databases).
            </li>
            <li>
              <strong>Email delivery</strong> providers that send transactional mail from addresses
              such as no-reply@potatoaihub.com.
            </li>
          </ul>
          <p>
            We may disclose information if required by law, legal process, or to protect the
            safety, rights, or property of PotatoAIHub, our users, or others.
          </p>

          <h2>5. Cookies and local storage</h2>
          <p>
            The web app uses local browser storage (and similar mechanisms in mobile WebViews) to
            keep you signed in and remember preferences. We do not use third-party advertising
            cookies to track you across unrelated sites for ads.
          </p>

          <h2>6. Data retention</h2>
          <p>
            We retain account, chat, usage, and billing records for as long as your account is
            active and as needed to provide the Service, resolve disputes, enforce agreements,
            and meet legal, tax, or accounting requirements. If you delete your account or
            request deletion, we will delete or anonymise personal data within a reasonable
            period, except where we must retain certain records (for example payment history)
            or where content remains available via a share link you created until that link
            expires or is revoked.
          </p>

          <h2>7. Security</h2>
          <p>
            We use industry-standard measures such as encrypted transport (HTTPS), hashed
            passwords, and access controls. No method of transmission or storage is completely
            secure; we cannot guarantee absolute security.
          </p>

          <h2>8. Your rights and choices</h2>
          <p>Depending on where you live, you may have rights to:</p>
          <ul>
            <li>Access or receive a copy of personal data we hold about you</li>
            <li>Correct inaccurate information</li>
            <li>Request deletion of your account or certain data</li>
            <li>Object to or restrict certain processing</li>
            <li>Withdraw consent where processing is based on consent</li>
          </ul>
          <p>
            You can update profile details in Settings, and manage email preferences where
            available. To exercise privacy rights or request account deletion, contact{' '}
            <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. We may need to verify your
            identity before fulfilling a request.
          </p>

          <h2>9. Children</h2>
          <p>
            The Service is not directed to children under 13 (or the minimum age required in
            your jurisdiction). We do not knowingly collect personal information from children.
            If you believe a child has provided us data, contact us and we will take appropriate
            steps to delete it.
          </p>

          <h2>10. International transfers</h2>
          <p>
            We may process and store information in countries other than where you live,
            including where our hosting or AI providers operate. Where required, we use
            appropriate safeguards for cross-border transfers.
          </p>

          <h2>11. Changes to this policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will post the revised
            version on this page and update the &ldquo;Last updated&rdquo; date. Continued use of
            the Service after changes become effective constitutes acceptance of the updated
            policy.
          </p>

          <h2>12. Contact</h2>
          <p>
            Privacy questions or requests:{' '}
            <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>
            <br />
            Website: <a href={SITE_URL}>{SITE_URL}</a>
          </p>
        </div>
      </main>

      <footer className="border-t border-surface-3 bg-surface-1 px-6 py-6 text-center text-sm text-gray-500">
        <p className="mb-2">© {new Date().getFullYear()} PotatoAIHub · PotatoChat</p>
        <Link to="/login" className="text-potato-500 hover:text-potato-400">
          Back to sign in
        </Link>
      </footer>
    </div>
  );
}
